### ISSUE TITLE
CRUD for Tablets

### ISSUE THREAD

**Issue by RSHKDL** [RSHKDL/p7-rest-api#12]
> As a BileMo retailer, I want to sell tablets in addition to phones.

### Acceptance criteria

- It's done when an authenticated retailer can manage a tablet product.

### Technical notes

We are going to create the following routes:

- `get_tablets_list`
- `get_tablets`
- `post_tablets`
- `patch_tablets`
- `delete_tablets`

We need to create a new entity, Tablet which extends a new AbstractProduct class.

_Specs are the same as the phones for now_ :ok_hand: 

### Tasks

- [x] create Tablet entity
- [x] create Tablet repository
- [x] create Tablet formtype
- [x] create Tablet model
- [x] create Tablet serializer
- [x] create the routes
- [x] create the new AbstractProduct class
