### ISSUE TITLE
Hypermedia Control (HAETOAS)

### ISSUE THREAD

**Issue by RSHKDL** [RSHKDL/p7-rest-api#15]
### Description

We only use _"links"_ has hypermedia, no _"embedded"_ so it will be a really light [Hal+Json](http://stateless.co/hal_specification.html)
Links goes under "_links" hash.

**Hypermedia in Collections**
- Pagination links (self, first, last, previous, next)
- Uri for each ressource in collection
```
{
   "uuid":"aze-rty-uio",
   "model":"a model name",
   "_links": {
       "product": { "href":"example.com/products/phones/aze-rty-uio" }
   }
}
```
**Hypermedia in Ressource**
- Uri for the ressource collection
Exemple : 
```
{
   "uuid":"aze-rty-uio",
   "model":"a model name",
   "price":20,
   "_links": {
       "collection": { "href":"example.com/products/phones" }
   }
}
```
Need to add a lot more [actions](https://fr.wikipedia.org/wiki/HATEOAS) : 
- retailer : add a client, see all clients
- client : edit, delete, see all
- all clients : see one, (edit one, delete one)
- product : edit, delete, see all
- all products : see one, (edit one, delete one)
 
### Tasks

- [x] Add pagination links
- [x] Add uri for ressource in collection
- [x] Add uri for collection in ressource
