### ISSUE TITLE
As a BileMo retailer, I want to see my own clients so I can manage them.

### ISSUE THREAD

**Issue by RSHKDL** [RSHKDL/p7-rest-api#8]
> As a BileMo retailer, I want to see my own clients so I can manage them.

### Acceptance criteria

- It's done when an authenticated retailer can see all his registered clients.
- It's done when an authenticated retailer can add, edit and remove a client.

### Technical notes

We are going to create the following routes:

- `get_retailer_clients_list` with argument `retailer_uuid` and code `200`
- `get_retailer_clients` with arguments `retailer_uuid` and `client_uuid` and code `200`
- `post_retailer_clients` with argument `retailer_uuid` and code `201`
- `patch_retailer_clients` with arguments `retailer_uuid` and `client_uuid` and code `200`
- `delete_retailer_clients` with arguments `retailer_uuid` and `client_uuid` and code `204`

We need to create two new entities, Retailer and Client which both extend our basic User.
The email property must become the unique identifier of all "users".

- Remove the username propety from User and adapt the security provider to use the email property on authentication.
- Add the Retailer Entity
- Add the Client Entity

_Specs for both are in the UML class diagrams_ :ok_hand: 

### Tasks

- [x] create the routes and their factory
- [x] update User entity and change authentication from username to email
- [x] create Retailer entity
- [x] create Client entity

**Comment by RSHKDL** [comment]
Done with PR #20

**Comment by RSHKDL** [comment]
Done with PR #20
